# FloodSegmentationAgent-HighPerf (v2026)

Notebook ini mengimplementasikan arsitektur performa tinggi untuk segmentasi banjir:

- Encoder: EfficientNet-B0 (ImageNet pretrained)
- Decoder: Attention U-Net dengan CBAM
- Skip connection: U-Net++ (nested dense skip)
- Bottleneck: Multi-Head Self-Attention
- Loss: Dice + BCE + Boundary loss
- Optimizer: AdamW
- Scheduler: Warmup + Cosine Annealing
- Post-processing: TTA + DenseCRF (opsional)

Catatan: target IoU 0.92-0.97 adalah target eksperimen, hasil aktual bergantung pada split data, kualitas label, dan hardware/runtime.

In [1]:
!nvidia-smi

Mon Mar 30 07:27:26 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.105.08             Driver Version: 580.105.08     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   36C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  Tesla T4                       Off |   00000000:00:05.0 Off |                    0 |
| N/A   37C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [50]:
# Install dependencies
%pip install -q --upgrade torch torchvision timm albumentations opencv-python matplotlib pandas numpy scikit-learn kagglehub pillow tqdm

# Optional DenseCRF (boleh gagal install di beberapa runtime)
import sys
import subprocess
subprocess.run([sys.executable, "-m", "pip", "install", "-q", "pydensecrf"], check=False)

CompletedProcess(args=['/usr/bin/python3', '-m', 'pip', 'install', '-q', 'pydensecrf'], returncode=1)

In [51]:
import os
import cv2
import math
import random
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
from tqdm.auto import tqdm

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split

import albumentations as A
from albumentations.pytorch import ToTensorV2
import timm
import kagglehub

try:
    import pydensecrf.densecrf as dcrf
    from pydensecrf.utils import unary_from_softmax
    HAS_DCRF = True
except Exception:
    HAS_DCRF = False

warnings.filterwarnings("ignore")

CONFIG = {
    "SEED": 42,
    "BATCH_SIZE": 16,  # effective batch size target
    "MICRO_BATCH_SIZE": 2,  # fallback aman untuk GPU terbatas
    "EPOCHS": 150,
    "FREEZE_EPOCHS": 30,
    "LR": 1e-4,
    "LR_UNFREEZE": 1e-5,
    "WEIGHT_DECAY": 1e-5,
    "IMAGE_HEIGHT": 512,
    "IMAGE_WIDTH": 512,
    "VAL_SIZE": 0.2,
    "NUM_WORKERS": 8,
    "CUTMIX_PROB": 0.3,
    "CUTMIX_ALPHA": 1.0,
    "WARMUP_EPOCHS": 5,
    "CHECKPOINT_PATH": "floodseg_highperf_best.pth",
    "DEVICE": "cuda" if torch.cuda.is_available() else "cpu",
}

print(f"Device: {CONFIG['DEVICE']}")
print(f"DenseCRF available: {HAS_DCRF}")

Device: cuda
DenseCRF available: False

In [52]:
# Optional authentication untuk akses dataset Kaggle
try:
    kagglehub.login()
except Exception as e:
    print("Login Kaggle opsional, lanjut jika dataset publik/cache tersedia.")
    print("Detail:", str(e)[:200])

VBox(children=(HTML(value='<center> <img\nsrc=https://www.kaggle.com/static/images/site-logo.png\nalt=\'Kaggle…

In [53]:
def set_seed(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.benchmark = True
    torch.backends.cudnn.deterministic = False


def clean_name(value):
    return str(value).strip().replace("\\", "/")


def resolve_existing_path(base_dir, root_dir, file_name):
    if os.path.isabs(file_name) and os.path.exists(file_name):
        return file_name

    candidates = [
        os.path.join(base_dir, file_name),
        os.path.join(root_dir, file_name),
        os.path.join(base_dir, os.path.basename(file_name)),
    ]

    for candidate in candidates:
        if os.path.exists(candidate):
            return candidate
    return candidates[0]


def read_image_rgb(img_path):
    image = cv2.imread(img_path, cv2.IMREAD_COLOR)
    if image is not None:
        return cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    try:
        with Image.open(img_path) as img:
            return np.array(img.convert("RGB"))
    except Exception:
        return None


def read_mask_gray(mask_path):
    mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
    if mask is not None:
        return mask

    try:
        with Image.open(mask_path) as m:
            return np.array(m.convert("L"))
    except Exception:
        return None


set_seed(CONFIG["SEED"])

In [54]:
# Dataset source sama seperti notebook UNET
dataset_root = kagglehub.dataset_download("faizalkarim/flood-area-segmentation")
print(f"Dataset root: {dataset_root}")

csv_path = os.path.join(dataset_root, "metadata.csv")
image_dir = os.path.join(dataset_root, "Image")
mask_dir = os.path.join(dataset_root, "Mask")
root_dir = os.path.dirname(image_dir)

metadata = pd.read_csv(csv_path)
valid_samples = []
missing_count = 0
decode_fail_count = 0

for i in range(len(metadata)):
    img_name = clean_name(metadata.iloc[i, 0])
    mask_name = clean_name(metadata.iloc[i, 1])

    img_path = resolve_existing_path(image_dir, root_dir, img_name)
    mask_path = resolve_existing_path(mask_dir, root_dir, mask_name)

    if not (os.path.isfile(img_path) and os.path.isfile(mask_path)):
        missing_count += 1
        continue

    image = read_image_rgb(img_path)
    mask = read_mask_gray(mask_path)
    if image is None or mask is None:
        decode_fail_count += 1
        continue

    valid_samples.append((img_path, mask_path))

if len(valid_samples) == 0:
    raise RuntimeError("Tidak ada sample valid. Cek path dataset/metadata.")

train_samples, val_samples = train_test_split(
    valid_samples,
    test_size=CONFIG["VAL_SIZE"],
    random_state=CONFIG["SEED"],
    shuffle=True,
 )

print(f"Total metadata: {len(metadata)}")
print(f"Valid samples: {len(valid_samples)}")
print(f"Missing file skipped: {missing_count}")
print(f"Decode fail skipped: {decode_fail_count}")
print(f"Train: {len(train_samples)} | Val: {len(val_samples)}")

Using Colab cache for faster access to the 'flood-area-segmentation' dataset.
Dataset root: /kaggle/input/flood-area-segmentation
Total metadata: 290
Valid samples: 290
Missing file skipped: 0
Decode fail skipped: 0
Train: 232 | Val: 58

In [55]:
class FloodDataset(Dataset):
    def __init__(self, samples, transform=None):
        self.samples = samples
        self.transform = transform

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, mask_path = self.samples[idx]

        image = read_image_rgb(img_path)
        mask = read_mask_gray(mask_path)

        if image is None:
            raise FileNotFoundError(f"Gagal membaca image pada idx={idx}: {img_path}")
        if mask is None:
            raise FileNotFoundError(f"Gagal membaca mask pada idx={idx}: {mask_path}")

        if image.ndim == 2:
            image = np.stack([image] * 3, axis=-1)

        mask = cv2.resize(mask, (image.shape[1], image.shape[0]), interpolation=cv2.INTER_NEAREST)
        mask = (mask > 127).astype(np.float32)

        if self.transform:
            augmented = self.transform(image=image, mask=mask)
            image = augmented["image"]
            mask = augmented["mask"]

        mask = mask.unsqueeze(0).float()
        return image, mask


train_transform = A.Compose(
    [
        A.Resize(CONFIG["IMAGE_HEIGHT"], CONFIG["IMAGE_WIDTH"]),
        A.HorizontalFlip(p=0.5),
        A.VerticalFlip(p=0.3),
        A.ShiftScaleRotate(
            shift_limit=0.10,
            scale_limit=0.20,
            rotate_limit=30,
            border_mode=cv2.BORDER_REFLECT_101,
            p=0.6,
        ),
        A.RandomBrightnessContrast(p=0.5),
        A.RandomGamma(p=0.3),
        A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
        ToTensorV2(),
    ],
    is_check_shapes=False,
 )

val_transform = A.Compose(
    [
        A.Resize(CONFIG["IMAGE_HEIGHT"], CONFIG["IMAGE_WIDTH"]),
        A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
        ToTensorV2(),
    ],
    is_check_shapes=False,
 )

train_dataset = FloodDataset(train_samples, transform=train_transform)
val_dataset = FloodDataset(val_samples, transform=val_transform)

num_workers = min(CONFIG["NUM_WORKERS"], os.cpu_count() or 2)
pin_memory = CONFIG["DEVICE"] == "cuda"

train_loader = DataLoader(
    train_dataset,
    batch_size=CONFIG["MICRO_BATCH_SIZE"],
    shuffle=True,
    num_workers=num_workers,
    pin_memory=pin_memory,
    drop_last=True,
 )
val_loader = DataLoader(
    val_dataset,
    batch_size=CONFIG["MICRO_BATCH_SIZE"],
    shuffle=False,
    num_workers=num_workers,
    pin_memory=pin_memory,
    drop_last=False,
 )

effective_batch = CONFIG["BATCH_SIZE"]
micro_batch = CONFIG["MICRO_BATCH_SIZE"]
accum_steps = max(1, math.ceil(effective_batch / micro_batch))
print(
    f"num_workers={num_workers} | train_batches={len(train_loader)} | val_batches={len(val_loader)} | "
    f"micro_batch={micro_batch} | effective_batch~{micro_batch * accum_steps} (accum_steps={accum_steps})"
)

num_workers=2 | train_batches=116 | val_batches=29 | micro_batch=2 | effective_batch~16 (accum_steps=8)

In [56]:
class ConvBlock(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
        )

    def forward(self, x):
        return self.block(x)


class ChannelAttention(nn.Module):
    def __init__(self, channels, reduction=16):
        super().__init__()
        hidden = max(channels // reduction, 8)
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.max_pool = nn.AdaptiveMaxPool2d(1)
        self.mlp = nn.Sequential(
            nn.Conv2d(channels, hidden, kernel_size=1, bias=False),
            nn.ReLU(inplace=True),
            nn.Conv2d(hidden, channels, kernel_size=1, bias=False),
        )
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        out = self.mlp(self.avg_pool(x)) + self.mlp(self.max_pool(x))
        return self.sigmoid(out)


class SpatialAttention(nn.Module):
    def __init__(self, kernel_size=7):
        super().__init__()
        padding = kernel_size // 2
        self.conv = nn.Conv2d(2, 1, kernel_size=kernel_size, padding=padding, bias=False)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        avg_out = torch.mean(x, dim=1, keepdim=True)
        max_out, _ = torch.max(x, dim=1, keepdim=True)
        out = torch.cat([avg_out, max_out], dim=1)
        out = self.conv(out)
        return self.sigmoid(out)


class CBAM(nn.Module):
    def __init__(self, channels, reduction=16):
        super().__init__()
        self.ca = ChannelAttention(channels, reduction=reduction)
        self.sa = SpatialAttention()

    def forward(self, x):
        x = x * self.ca(x)
        x = x * self.sa(x)
        return x


class AttentionGate(nn.Module):
    def __init__(self, skip_channels, gate_channels, inter_channels):
        super().__init__()
        self.theta = nn.Conv2d(skip_channels, inter_channels, kernel_size=1, bias=False)
        self.phi = nn.Conv2d(gate_channels, inter_channels, kernel_size=1, bias=False)
        self.psi = nn.Conv2d(inter_channels, 1, kernel_size=1, bias=True)
        self.relu = nn.ReLU(inplace=True)
        self.sigmoid = nn.Sigmoid()

    def forward(self, skip, gate):
        if gate.shape[-2:] != skip.shape[-2:]:
            gate = F.interpolate(gate, size=skip.shape[-2:], mode="bilinear", align_corners=False)
        attn = self.relu(self.theta(skip) + self.phi(gate))
        attn = self.sigmoid(self.psi(attn))
        return skip * attn


class MHSA2DBottleneck(nn.Module):
    def __init__(self, channels, num_heads=8, dropout=0.1):
        super().__init__()
        self.norm1 = nn.LayerNorm(channels)
        self.attn = nn.MultiheadAttention(
            embed_dim=channels,
            num_heads=num_heads,
            dropout=dropout,
            batch_first=True,
        )
        self.norm2 = nn.LayerNorm(channels)
        self.ffn = nn.Sequential(
            nn.Linear(channels, channels * 4),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(channels * 4, channels),
        )

    def forward(self, x):
        b, c, h, w = x.shape
        seq = x.flatten(2).transpose(1, 2)  # [B, N, C]

        attn_in = self.norm1(seq)
        attn_out, _ = self.attn(attn_in, attn_in, attn_in, need_weights=False)
        seq = seq + attn_out

        ffn_in = self.norm2(seq)
        seq = seq + self.ffn(ffn_in)

        return seq.transpose(1, 2).reshape(b, c, h, w)


class HighPerfFloodUNetPP(nn.Module):
    def __init__(self, num_classes=1, pretrained=True):
        super().__init__()
        self.encoder = timm.create_model(
            "efficientnet_b0",
            pretrained=pretrained,
            features_only=True,
            out_indices=(0, 1, 2, 3, 4),
        )

        enc_ch = self.encoder.feature_info.channels()  # expected: [16,24,40,112,320]
        dec_ch = [32, 64, 128, 256, 320]

        self.proj0 = nn.Conv2d(enc_ch[0], dec_ch[0], kernel_size=1)
        self.proj1 = nn.Conv2d(enc_ch[1], dec_ch[1], kernel_size=1)
        self.proj2 = nn.Conv2d(enc_ch[2], dec_ch[2], kernel_size=1)
        self.proj3 = nn.Conv2d(enc_ch[3], dec_ch[3], kernel_size=1)
        self.proj4 = nn.Conv2d(enc_ch[4], dec_ch[4], kernel_size=1)

        self.cbam0 = CBAM(dec_ch[0])
        self.cbam1 = CBAM(dec_ch[1])
        self.cbam2 = CBAM(dec_ch[2])
        self.cbam3 = CBAM(dec_ch[3])
        self.cbam4 = CBAM(dec_ch[4])

        self.ag0 = AttentionGate(dec_ch[0], dec_ch[1], inter_channels=16)
        self.ag1 = AttentionGate(dec_ch[1], dec_ch[2], inter_channels=32)
        self.ag2 = AttentionGate(dec_ch[2], dec_ch[3], inter_channels=64)
        self.ag3 = AttentionGate(dec_ch[3], dec_ch[4], inter_channels=128)

        self.mhsa = MHSA2DBottleneck(dec_ch[4], num_heads=8, dropout=0.1)

        self.conv0_1 = ConvBlock(dec_ch[0] + dec_ch[1], dec_ch[0])
        self.conv1_1 = ConvBlock(dec_ch[1] + dec_ch[2], dec_ch[1])
        self.conv2_1 = ConvBlock(dec_ch[2] + dec_ch[3], dec_ch[2])
        self.conv3_1 = ConvBlock(dec_ch[3] + dec_ch[4], dec_ch[3])

        self.conv0_2 = ConvBlock(dec_ch[0] * 2 + dec_ch[1], dec_ch[0])
        self.conv1_2 = ConvBlock(dec_ch[1] * 2 + dec_ch[2], dec_ch[1])
        self.conv2_2 = ConvBlock(dec_ch[2] * 2 + dec_ch[3], dec_ch[2])

        self.conv0_3 = ConvBlock(dec_ch[0] * 3 + dec_ch[1], dec_ch[0])
        self.conv1_3 = ConvBlock(dec_ch[1] * 3 + dec_ch[2], dec_ch[1])

        self.conv0_4 = ConvBlock(dec_ch[0] * 4 + dec_ch[1], dec_ch[0])

        self.head = nn.Conv2d(dec_ch[0], num_classes, kernel_size=1)

    @staticmethod
    def _up(x, target):
        return F.interpolate(x, size=target.shape[-2:], mode="bilinear", align_corners=False)

    def forward(self, x):
        input_hw = x.shape[-2:]

        feats = self.encoder(x)
        x0_0 = self.cbam0(self.proj0(feats[0]))
        x1_0 = self.cbam1(self.proj1(feats[1]))
        x2_0 = self.cbam2(self.proj2(feats[2]))
        x3_0 = self.cbam3(self.proj3(feats[3]))
        x4_0 = self.cbam4(self.proj4(feats[4]))
        x4_0 = self.mhsa(x4_0)

        s0 = self.ag0(x0_0, x1_0)
        s1 = self.ag1(x1_0, x2_0)
        s2 = self.ag2(x2_0, x3_0)
        s3 = self.ag3(x3_0, x4_0)

        x0_1 = self.conv0_1(torch.cat([s0, self._up(x1_0, x0_0)], dim=1))
        x1_1 = self.conv1_1(torch.cat([s1, self._up(x2_0, x1_0)], dim=1))
        x2_1 = self.conv2_1(torch.cat([s2, self._up(x3_0, x2_0)], dim=1))
        x3_1 = self.conv3_1(torch.cat([s3, self._up(x4_0, x3_0)], dim=1))

        x0_2 = self.conv0_2(torch.cat([x0_0, x0_1, self._up(x1_1, x0_0)], dim=1))
        x1_2 = self.conv1_2(torch.cat([x1_0, x1_1, self._up(x2_1, x1_0)], dim=1))
        x2_2 = self.conv2_2(torch.cat([x2_0, x2_1, self._up(x3_1, x2_0)], dim=1))

        x0_3 = self.conv0_3(torch.cat([x0_0, x0_1, x0_2, self._up(x1_2, x0_0)], dim=1))
        x1_3 = self.conv1_3(torch.cat([x1_0, x1_1, x1_2, self._up(x2_2, x1_0)], dim=1))

        x0_4 = self.conv0_4(torch.cat([x0_0, x0_1, x0_2, x0_3, self._up(x1_3, x0_0)], dim=1))

        logits = self.head(x0_4)
        logits = F.interpolate(logits, size=input_hw, mode="bilinear", align_corners=False)
        return logits


model = HighPerfFloodUNetPP(num_classes=1, pretrained=True).to(CONFIG["DEVICE"])
num_params = sum(p.numel() for p in model.parameters()) / 1e6
print(f"Model params: {num_params:.2f}M")

with torch.no_grad():
    dummy = torch.randn(1, 3, CONFIG["IMAGE_HEIGHT"], CONFIG["IMAGE_WIDTH"]).to(CONFIG["DEVICE"])
    out = model(dummy)
print("Dummy output shape:", out.shape)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

Model params: 9.10M
Dummy output shape: torch.Size([1, 1, 512, 512])

In [57]:
def dice_loss_with_logits(logits, targets, eps=1e-6):
    probs = torch.sigmoid(logits)
    dims = (1, 2, 3)
    intersection = (probs * targets).sum(dim=dims)
    union = probs.sum(dim=dims) + targets.sum(dim=dims)
    dice = (2.0 * intersection + eps) / (union + eps)
    return 1.0 - dice


def mask_boundary(mask):
    # Morphological gradient approximation
    max_pool = F.max_pool2d(mask, kernel_size=3, stride=1, padding=1)
    min_pool = -F.max_pool2d(-mask, kernel_size=3, stride=1, padding=1)
    return (max_pool - min_pool).clamp(0.0, 1.0)


def combined_segmentation_loss(logits, targets, w_dice=1.0, w_bce=1.0, w_boundary=0.5):
    dice_term = dice_loss_with_logits(logits, targets).mean()
    bce_term = F.binary_cross_entropy_with_logits(logits, targets)

    probs = torch.sigmoid(logits)
    pred_boundary = mask_boundary(probs)
    true_boundary = mask_boundary(targets)
    boundary_term = F.binary_cross_entropy(pred_boundary, true_boundary)

    total = w_dice * dice_term + w_bce * bce_term + w_boundary * boundary_term
    parts = {
        "dice": float(dice_term.item()),
        "bce": float(bce_term.item()),
        "boundary": float(boundary_term.item()),
    }
    return total, parts


def iou_score_from_logits(logits, targets, threshold=0.5, eps=1e-8):
    preds = (torch.sigmoid(logits) > threshold).float()
    intersection = (preds * targets).sum(dim=(1, 2, 3))
    union = preds.sum(dim=(1, 2, 3)) + targets.sum(dim=(1, 2, 3)) - intersection
    iou = (intersection + eps) / (union + eps)
    return float(iou.mean().item())


def precision_recall_f1_from_logits(logits, targets, threshold=0.5, eps=1e-8):
    preds = (torch.sigmoid(logits) > threshold).float()
    tp = (preds * targets).sum()
    fp = (preds * (1 - targets)).sum()
    fn = ((1 - preds) * targets).sum()

    precision = (tp + eps) / (tp + fp + eps)
    recall = (tp + eps) / (tp + fn + eps)
    f1 = 2 * precision * recall / (precision + recall + eps)
    return float(precision.item()), float(recall.item()), float(f1.item())


def rand_bbox(size, lam):
    _, _, h, w = size
    cut_ratio = np.sqrt(1.0 - lam)
    cut_w = int(w * cut_ratio)
    cut_h = int(h * cut_ratio)

    cx = np.random.randint(w)
    cy = np.random.randint(h)

    x1 = np.clip(cx - cut_w // 2, 0, w)
    y1 = np.clip(cy - cut_h // 2, 0, h)
    x2 = np.clip(cx + cut_w // 2, 0, w)
    y2 = np.clip(cy + cut_h // 2, 0, h)
    return x1, y1, x2, y2


def apply_cutmix(images, masks, p=0.3, alpha=1.0):
    if np.random.rand() > p or images.size(0) < 2:
        return images, masks

    lam = np.random.beta(alpha, alpha)
    rand_index = torch.randperm(images.size(0), device=images.device)
    x1, y1, x2, y2 = rand_bbox(images.size(), lam)

    images = images.clone()
    masks = masks.clone()
    images[:, :, y1:y2, x1:x2] = images[rand_index, :, y1:y2, x1:x2]
    masks[:, :, y1:y2, x1:x2] = masks[rand_index, :, y1:y2, x1:x2]
    return images, masks


def freeze_encoder(model, freeze=True):
    for p in model.encoder.parameters():
        p.requires_grad = not freeze


def build_optimizer(model, encoder_lr, decoder_lr, weight_decay):
    encoder_params = []
    decoder_params = []
    for name, p in model.named_parameters():
        if not p.requires_grad:
            continue
        if name.startswith("encoder."):
            encoder_params.append(p)
        else:
            decoder_params.append(p)

    param_groups = [{"params": decoder_params, "lr": decoder_lr}]
    if len(encoder_params) > 0 and encoder_lr is not None:
        param_groups.append({"params": encoder_params, "lr": encoder_lr})

    optimizer = torch.optim.AdamW(param_groups, weight_decay=weight_decay)
    return optimizer


def build_warmup_cosine_scheduler(optimizer, total_epochs, warmup_epochs):
    warmup_epochs = min(warmup_epochs, max(total_epochs - 1, 1))

    def lr_lambda(epoch_idx):
        if epoch_idx < warmup_epochs:
            return float(epoch_idx + 1) / float(max(1, warmup_epochs))
        progress = (epoch_idx - warmup_epochs) / float(max(1, total_epochs - warmup_epochs))
        return 0.5 * (1.0 + math.cos(math.pi * progress))

    return torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda=lr_lambda)


@torch.no_grad()
def validate_one_epoch(model, loader, device):
    model.eval()
    total_loss = 0.0
    total_iou = 0.0
    total_precision = 0.0
    total_recall = 0.0
    total_f1 = 0.0

    for images, masks in loader:
        images = images.to(device, non_blocking=True)
        masks = masks.to(device, non_blocking=True)

        logits = model(images)
        loss, _ = combined_segmentation_loss(logits, masks)

        total_loss += float(loss.item())
        total_iou += iou_score_from_logits(logits, masks)
        p, r, f1 = precision_recall_f1_from_logits(logits, masks)
        total_precision += p
        total_recall += r
        total_f1 += f1

    n = max(len(loader), 1)
    return {
        "loss": total_loss / n,
        "iou": total_iou / n,
        "precision": total_precision / n,
        "recall": total_recall / n,
        "f1": total_f1 / n,
    }

In [58]:
def train_highperf(model, train_loader, val_loader, config):
    device = config["DEVICE"]
    use_amp = device == "cuda"
    scaler = torch.amp.GradScaler("cuda", enabled=use_amp)

    micro_batch = config.get("MICRO_BATCH_SIZE", config["BATCH_SIZE"])
    accum_steps = max(1, math.ceil(config["BATCH_SIZE"] / micro_batch))
    max_steps = config.get("MAX_STEPS_PER_EPOCH", None)

    freeze_epochs = min(config["FREEZE_EPOCHS"], config["EPOCHS"])
    best_val_iou = -1.0
    history = []

    # Phase 1: freeze encoder
    freeze_encoder(model, freeze=True)
    optimizer = build_optimizer(
        model,
        encoder_lr=None,
        decoder_lr=config["LR"],
        weight_decay=config["WEIGHT_DECAY"],
    )
    scheduler = build_warmup_cosine_scheduler(
        optimizer,
        total_epochs=max(freeze_epochs, 1),
        warmup_epochs=config["WARMUP_EPOCHS"],
    )

    print("Mulai training phase-1 (encoder frozen)")
    print(
        f"Gradient accumulation aktif: micro_batch={micro_batch}, "
        f"target_batch={config['BATCH_SIZE']}, accum_steps={accum_steps}"
    )

    for epoch in range(config["EPOCHS"]):
        if epoch == freeze_epochs and freeze_epochs < config["EPOCHS"]:
            # Phase 2: unfreeze encoder
            freeze_encoder(model, freeze=False)
            optimizer = build_optimizer(
                model,
                encoder_lr=config["LR_UNFREEZE"],
                decoder_lr=config["LR"],
                weight_decay=config["WEIGHT_DECAY"],
            )
            scheduler = build_warmup_cosine_scheduler(
                optimizer,
                total_epochs=max(config["EPOCHS"] - freeze_epochs, 1),
                warmup_epochs=min(config["WARMUP_EPOCHS"], max(config["EPOCHS"] - freeze_epochs - 1, 1)),
            )
            print("Masuk phase-2 (encoder unfrozen)")

        model.train()
        running_loss = 0.0
        running_iou = 0.0

        optimizer.zero_grad(set_to_none=True)
        pbar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{config['EPOCHS']}", leave=False)
        for step_idx, (images, masks) in enumerate(pbar):
            images = images.to(device, non_blocking=True)
            masks = masks.to(device, non_blocking=True)

            images, masks = apply_cutmix(
                images,
                masks,
                p=config["CUTMIX_PROB"],
                alpha=config["CUTMIX_ALPHA"],
            )

            with torch.autocast(device_type="cuda" if use_amp else "cpu", enabled=use_amp):
                logits = model(images)

            # Hitung loss di luar autocast agar BCE boundary aman
            loss, loss_parts = combined_segmentation_loss(logits.float(), masks.float())
            loss_for_backward = loss / accum_steps

            scaler.scale(loss_for_backward).backward()

            # Step optimizer setiap accum_steps (atau batch terakhir)
            is_update_step = ((step_idx + 1) % accum_steps == 0) or ((step_idx + 1) == len(train_loader))
            if is_update_step:
                scaler.step(optimizer)
                scaler.update()
                optimizer.zero_grad(set_to_none=True)

            batch_iou = iou_score_from_logits(logits.detach(), masks)
            running_loss += float(loss.item())
            running_iou += batch_iou

            pbar.set_postfix(
                loss=f"{loss.item():.4f}",
                iou=f"{batch_iou:.4f}",
                d=f"{loss_parts['dice']:.4f}",
                b=f"{loss_parts['bce']:.4f}",
                edge=f"{loss_parts['boundary']:.4f}",
            )

            if max_steps is not None and (step_idx + 1) >= max_steps:
                # Pastikan grad terakhir tetap di-step jika break sebelum is_update_step
                if not is_update_step:
                    scaler.step(optimizer)
                    scaler.update()
                    optimizer.zero_grad(set_to_none=True)
                break

        scheduler.step()

        denom = max(1, (step_idx + 1) if max_steps is not None else len(train_loader))
        train_loss = running_loss / denom
        train_iou = running_iou / denom
        val_metrics = validate_one_epoch(model, val_loader, device)

        current_lr = optimizer.param_groups[0]["lr"]
        log_line = (
            f"Epoch [{epoch+1}/{config['EPOCHS']}] | "
            f"LR: {current_lr:.2e} | "
            f"Train Loss: {train_loss:.4f} | Train IoU: {train_iou:.4f} | "
            f"Val Loss: {val_metrics['loss']:.4f} | Val IoU: {val_metrics['iou']:.4f} | "
            f"Val F1: {val_metrics['f1']:.4f}"
        )
        print(log_line)

        history.append(
            {
                "epoch": epoch + 1,
                "lr": current_lr,
                "train_loss": train_loss,
                "train_iou": train_iou,
                "val_loss": val_metrics["loss"],
                "val_iou": val_metrics["iou"],
                "val_precision": val_metrics["precision"],
                "val_recall": val_metrics["recall"],
                "val_f1": val_metrics["f1"],
            }
        )

        if val_metrics["iou"] > best_val_iou:
            best_val_iou = val_metrics["iou"]
            torch.save(
                {
                    "model_state_dict": model.state_dict(),
                    "config": config,
                    "best_val_iou": best_val_iou,
                    "epoch": epoch + 1,
                },
                config["CHECKPOINT_PATH"],
            )
            print(f"Checkpoint terbaik disimpan (Val IoU={best_val_iou:.4f})")

    print("Training selesai.")
    return pd.DataFrame(history)

In [59]:
# Optional quick sanity run (1 epoch, beberapa step saja)
quick_cfg = dict(CONFIG)
quick_cfg["EPOCHS"] = 1
quick_cfg["FREEZE_EPOCHS"] = 0
quick_cfg["WARMUP_EPOCHS"] = 1
quick_cfg["MAX_STEPS_PER_EPOCH"] = 4
quick_cfg["CUTMIX_PROB"] = 0.0
history_quick = train_highperf(model, train_loader, val_loader, quick_cfg)
history_quick.tail()

Mulai training phase-1 (encoder frozen)
Gradient accumulation aktif: micro_batch=2, target_batch=16, accum_steps=8
Masuk phase-2 (encoder unfrozen)

Epoch 1/1:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [1/1] | LR: 1.00e-04 | Train Loss: 1.1798 | Train IoU: 0.5692 | Val Loss: 1.3276 | Val IoU: 0.4314 | Val F1: 0.5976
Checkpoint terbaik disimpan (Val IoU=0.4314)
Training selesai.

,epoch,lr,train_loss,train_iou,val_loss,val_iou,val_precision,val_recall,val_f1
0,1,0.0001,1.179804,0.569218,1.32757,0.431351,0.440528,0.96695,0.597617

In [60]:
# Full training run (sesuai CONFIG)
history_df = train_highperf(model, train_loader, val_loader, CONFIG)
history_df.tail()

Mulai training phase-1 (encoder frozen)
Gradient accumulation aktif: micro_batch=2, target_batch=16, accum_steps=8

Epoch 1/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [1/150] | LR: 4.00e-05 | Train Loss: 1.1933 | Train IoU: 0.5366 | Val Loss: 1.0739 | Val IoU: 0.6105 | Val F1: 0.7512
Checkpoint terbaik disimpan (Val IoU=0.6105)

Epoch 2/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [2/150] | LR: 6.00e-05 | Train Loss: 1.0795 | Train IoU: 0.6090 | Val Loss: 0.9286 | Val IoU: 0.7005 | Val F1: 0.8209
Checkpoint terbaik disimpan (Val IoU=0.7005)

Epoch 3/150:   0%|          | 0/116 [00:00<?, ?it/s]

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process

Epoch [3/150] | LR: 8.00e-05 | Train Loss: 0.9631 | Train IoU: 0.6555 | Val Loss: 0.8350 | Val IoU: 0.7416 | Val F1: 0.8527
Checkpoint terbaik disimpan (Val IoU=0.7416)

Epoch 4/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [4/150] | LR: 1.00e-04 | Train Loss: 0.9096 | Train IoU: 0.6679 | Val Loss: 0.7924 | Val IoU: 0.7328 | Val F1: 0.8439

Epoch 5/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [5/150] | LR: 1.00e-04 | Train Loss: 0.8822 | Train IoU: 0.6765 | Val Loss: 0.7699 | Val IoU: 0.7660 | Val F1: 0.8694
Checkpoint terbaik disimpan (Val IoU=0.7660)

Epoch 6/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [6/150] | LR: 9.96e-05 | Train Loss: 0.8503 | Train IoU: 0.6908 | Val Loss: 0.7482 | Val IoU: 0.7614 | Val F1: 0.8675

Epoch 7/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [7/150] | LR: 9.84e-05 | Train Loss: 0.8297 | Train IoU: 0.7032 | Val Loss: 0.7143 | Val IoU: 0.7752 | Val F1: 0.8759
Checkpoint terbaik disimpan (Val IoU=0.7752)

Epoch 8/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [8/150] | LR: 9.65e-05 | Train Loss: 0.8143 | Train IoU: 0.7059 | Val Loss: 0.7328 | Val IoU: 0.7731 | Val F1: 0.8748

Epoch 9/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [9/150] | LR: 9.38e-05 | Train Loss: 0.8022 | Train IoU: 0.7075 | Val Loss: 0.7028 | Val IoU: 0.7765 | Val F1: 0.8765
Checkpoint terbaik disimpan (Val IoU=0.7765)

Epoch 10/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [10/150] | LR: 9.05e-05 | Train Loss: 0.7815 | Train IoU: 0.7177 | Val Loss: 0.7007 | Val IoU: 0.7813 | Val F1: 0.8786
Checkpoint terbaik disimpan (Val IoU=0.7813)

Epoch 11/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [11/150] | LR: 8.64e-05 | Train Loss: 0.7721 | Train IoU: 0.7201 | Val Loss: 0.6940 | Val IoU: 0.7862 | Val F1: 0.8834
Checkpoint terbaik disimpan (Val IoU=0.7862)

Epoch 12/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [12/150] | LR: 8.19e-05 | Train Loss: 0.7562 | Train IoU: 0.7333 | Val Loss: 0.6881 | Val IoU: 0.7761 | Val F1: 0.8768

Epoch 13/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [13/150] | LR: 7.68e-05 | Train Loss: 0.7589 | Train IoU: 0.7256 | Val Loss: 0.7070 | Val IoU: 0.7653 | Val F1: 0.8684

Epoch 14/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [14/150] | LR: 7.13e-05 | Train Loss: 0.7441 | Train IoU: 0.7322 | Val Loss: 0.6722 | Val IoU: 0.7775 | Val F1: 0.8755

Epoch 15/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [15/150] | LR: 6.55e-05 | Train Loss: 0.7318 | Train IoU: 0.7412 | Val Loss: 0.6512 | Val IoU: 0.7938 | Val F1: 0.8874
Checkpoint terbaik disimpan (Val IoU=0.7938)

Epoch 16/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [16/150] | LR: 5.94e-05 | Train Loss: 0.7123 | Train IoU: 0.7508 | Val Loss: 0.6569 | Val IoU: 0.7905 | Val F1: 0.8848

Epoch 17/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [17/150] | LR: 5.31e-05 | Train Loss: 0.7180 | Train IoU: 0.7461 | Val Loss: 0.6672 | Val IoU: 0.7716 | Val F1: 0.8738

Epoch 18/150:   0%|          | 0/116 [00:00<?, ?it/s]

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
    self._shutdown_workers()  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers

if w.is_alive():
           ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process

Epoch [18/150] | LR: 4.69e-05 | Train Loss: 0.7054 | Train IoU: 0.7503 | Val Loss: 0.6540 | Val IoU: 0.7921 | Val F1: 0.8844

Epoch 19/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [19/150] | LR: 4.06e-05 | Train Loss: 0.7012 | Train IoU: 0.7520 | Val Loss: 0.6352 | Val IoU: 0.7963 | Val F1: 0.8879
Checkpoint terbaik disimpan (Val IoU=0.7963)

Epoch 20/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [20/150] | LR: 3.45e-05 | Train Loss: 0.6962 | Train IoU: 0.7550 | Val Loss: 0.6637 | Val IoU: 0.7852 | Val F1: 0.8817

Epoch 21/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [21/150] | LR: 2.87e-05 | Train Loss: 0.6943 | Train IoU: 0.7565 | Val Loss: 0.6601 | Val IoU: 0.7957 | Val F1: 0.8888

Epoch 22/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [22/150] | LR: 2.32e-05 | Train Loss: 0.6897 | Train IoU: 0.7593 | Val Loss: 0.6327 | Val IoU: 0.7987 | Val F1: 0.8900
Checkpoint terbaik disimpan (Val IoU=0.7987)

Epoch 23/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [23/150] | LR: 1.81e-05 | Train Loss: 0.6917 | Train IoU: 0.7596 | Val Loss: 0.6393 | Val IoU: 0.7939 | Val F1: 0.8864

Epoch 24/150:   0%|          | 0/116 [00:00<?, ?it/s]

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process

Epoch [24/150] | LR: 1.36e-05 | Train Loss: 0.6896 | Train IoU: 0.7556 | Val Loss: 0.6278 | Val IoU: 0.8006 | Val F1: 0.8908
Checkpoint terbaik disimpan (Val IoU=0.8006)

Epoch 25/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [25/150] | LR: 9.55e-06 | Train Loss: 0.6821 | Train IoU: 0.7611 | Val Loss: 0.6293 | Val IoU: 0.7961 | Val F1: 0.8888

Epoch 26/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [26/150] | LR: 6.18e-06 | Train Loss: 0.6690 | Train IoU: 0.7696 | Val Loss: 0.6569 | Val IoU: 0.7813 | Val F1: 0.8766

Epoch 27/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [27/150] | LR: 3.51e-06 | Train Loss: 0.6720 | Train IoU: 0.7691 | Val Loss: 0.6517 | Val IoU: 0.7949 | Val F1: 0.8879

Epoch 28/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [28/150] | LR: 1.57e-06 | Train Loss: 0.6695 | Train IoU: 0.7718 | Val Loss: 0.6238 | Val IoU: 0.7966 | Val F1: 0.8874

Epoch 29/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [29/150] | LR: 3.94e-07 | Train Loss: 0.6686 | Train IoU: 0.7685 | Val Loss: 0.6464 | Val IoU: 0.7853 | Val F1: 0.8802

Epoch 30/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [30/150] | LR: 0.00e+00 | Train Loss: 0.6785 | Train IoU: 0.7641 | Val Loss: 0.6383 | Val IoU: 0.7988 | Val F1: 0.8907
Masuk phase-2 (encoder unfrozen)

Epoch 31/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [31/150] | LR: 4.00e-05 | Train Loss: 0.6683 | Train IoU: 0.7709 | Val Loss: 0.6166 | Val IoU: 0.8003 | Val F1: 0.8911

Epoch 32/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [32/150] | LR: 6.00e-05 | Train Loss: 0.6685 | Train IoU: 0.7685 | Val Loss: 0.6451 | Val IoU: 0.7893 | Val F1: 0.8841

Epoch 33/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [33/150] | LR: 8.00e-05 | Train Loss: 0.6709 | Train IoU: 0.7647 | Val Loss: 0.6116 | Val IoU: 0.7971 | Val F1: 0.8897

Epoch 34/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [34/150] | LR: 1.00e-04 | Train Loss: 0.6589 | Train IoU: 0.7721 | Val Loss: 0.6319 | Val IoU: 0.7902 | Val F1: 0.8848

Epoch 35/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [35/150] | LR: 1.00e-04 | Train Loss: 0.6647 | Train IoU: 0.7593 | Val Loss: 0.6012 | Val IoU: 0.7941 | Val F1: 0.8876

Epoch 36/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [36/150] | LR: 1.00e-04 | Train Loss: 0.6558 | Train IoU: 0.7634 | Val Loss: 0.6499 | Val IoU: 0.7674 | Val F1: 0.8690

Epoch 37/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [37/150] | LR: 9.99e-05 | Train Loss: 0.6467 | Train IoU: 0.7734 | Val Loss: 0.5914 | Val IoU: 0.7960 | Val F1: 0.8867

Epoch 38/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [38/150] | LR: 9.98e-05 | Train Loss: 0.6425 | Train IoU: 0.7697 | Val Loss: 0.6024 | Val IoU: 0.7881 | Val F1: 0.8835

Epoch 39/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [39/150] | LR: 9.97e-05 | Train Loss: 0.6243 | Train IoU: 0.7774 | Val Loss: 0.6015 | Val IoU: 0.7927 | Val F1: 0.8838

Epoch 40/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [40/150] | LR: 9.95e-05 | Train Loss: 0.6371 | Train IoU: 0.7695 | Val Loss: 0.5838 | Val IoU: 0.8003 | Val F1: 0.8903

Epoch 41/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [41/150] | LR: 9.93e-05 | Train Loss: 0.6227 | Train IoU: 0.7743 | Val Loss: 0.5536 | Val IoU: 0.8057 | Val F1: 0.8941
Checkpoint terbaik disimpan (Val IoU=0.8057)

Epoch 42/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [42/150] | LR: 9.91e-05 | Train Loss: 0.6123 | Train IoU: 0.7826 | Val Loss: 0.5795 | Val IoU: 0.7921 | Val F1: 0.8825

Epoch 43/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [43/150] | LR: 9.88e-05 | Train Loss: 0.6126 | Train IoU: 0.7816 | Val Loss: 0.5666 | Val IoU: 0.8012 | Val F1: 0.8919

Epoch 44/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [44/150] | LR: 9.85e-05 | Train Loss: 0.6073 | Train IoU: 0.7840 | Val Loss: 0.5809 | Val IoU: 0.7997 | Val F1: 0.8899

Epoch 45/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [45/150] | LR: 9.81e-05 | Train Loss: 0.5774 | Train IoU: 0.7936 | Val Loss: 0.5662 | Val IoU: 0.7933 | Val F1: 0.8845

Epoch 46/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [46/150] | LR: 9.78e-05 | Train Loss: 0.5881 | Train IoU: 0.7844 | Val Loss: 0.5559 | Val IoU: 0.8006 | Val F1: 0.8892

Epoch 47/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [47/150] | LR: 9.73e-05 | Train Loss: 0.5838 | Train IoU: 0.7889 | Val Loss: 0.5655 | Val IoU: 0.7931 | Val F1: 0.8864

Epoch 48/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [48/150] | LR: 9.69e-05 | Train Loss: 0.5647 | Train IoU: 0.7983 | Val Loss: 0.5687 | Val IoU: 0.7969 | Val F1: 0.8894

Epoch 49/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [49/150] | LR: 9.64e-05 | Train Loss: 0.5690 | Train IoU: 0.7953 | Val Loss: 0.6067 | Val IoU: 0.7661 | Val F1: 0.8662

Epoch 50/150:   0%|          | 0/116 [00:00<?, ?it/s]

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process

Epoch [50/150] | LR: 9.59e-05 | Train Loss: 0.5570 | Train IoU: 0.7976 | Val Loss: 0.5512 | Val IoU: 0.7966 | Val F1: 0.8890

Epoch 51/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [51/150] | LR: 9.53e-05 | Train Loss: 0.5739 | Train IoU: 0.7890 | Val Loss: 0.5212 | Val IoU: 0.7996 | Val F1: 0.8902

Epoch 52/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [52/150] | LR: 9.47e-05 | Train Loss: 0.5601 | Train IoU: 0.7928 | Val Loss: 0.5347 | Val IoU: 0.7987 | Val F1: 0.8903

Epoch 53/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [53/150] | LR: 9.41e-05 | Train Loss: 0.5477 | Train IoU: 0.7952 | Val Loss: 0.5357 | Val IoU: 0.7937 | Val F1: 0.8884

Epoch 54/150:   0%|          | 0/116 [00:00<?, ?it/s]

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process

Epoch [54/150] | LR: 9.34e-05 | Train Loss: 0.5434 | Train IoU: 0.8022 | Val Loss: 0.5324 | Val IoU: 0.8017 | Val F1: 0.8926

Epoch 55/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [55/150] | LR: 9.27e-05 | Train Loss: 0.5400 | Train IoU: 0.7972 | Val Loss: 0.5124 | Val IoU: 0.8100 | Val F1: 0.8979
Checkpoint terbaik disimpan (Val IoU=0.8100)

Epoch 56/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [56/150] | LR: 9.20e-05 | Train Loss: 0.5476 | Train IoU: 0.7949 | Val Loss: 0.5174 | Val IoU: 0.7985 | Val F1: 0.8888

Epoch 57/150:   0%|          | 0/116 [00:00<?, ?it/s]

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process

Epoch [57/150] | LR: 9.12e-05 | Train Loss: 0.5480 | Train IoU: 0.7902 | Val Loss: 0.5024 | Val IoU: 0.8063 | Val F1: 0.8949

Epoch 58/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [58/150] | LR: 9.05e-05 | Train Loss: 0.5322 | Train IoU: 0.7994 | Val Loss: 0.5252 | Val IoU: 0.8000 | Val F1: 0.8909

Epoch 59/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [59/150] | LR: 8.96e-05 | Train Loss: 0.5307 | Train IoU: 0.7994 | Val Loss: 0.5076 | Val IoU: 0.8090 | Val F1: 0.8967

Epoch 60/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [60/150] | LR: 8.88e-05 | Train Loss: 0.5278 | Train IoU: 0.8001 | Val Loss: 0.5151 | Val IoU: 0.8045 | Val F1: 0.8947

Epoch 61/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [61/150] | LR: 8.79e-05 | Train Loss: 0.5185 | Train IoU: 0.8052 | Val Loss: 0.4987 | Val IoU: 0.8055 | Val F1: 0.8947

Epoch 62/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [62/150] | LR: 8.70e-05 | Train Loss: 0.5137 | Train IoU: 0.8102 | Val Loss: 0.5089 | Val IoU: 0.7969 | Val F1: 0.8897

Epoch 63/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [63/150] | LR: 8.61e-05 | Train Loss: 0.5093 | Train IoU: 0.8072 | Val Loss: 0.5079 | Val IoU: 0.8014 | Val F1: 0.8913

Epoch 64/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [64/150] | LR: 8.51e-05 | Train Loss: 0.5043 | Train IoU: 0.8103 | Val Loss: 0.4980 | Val IoU: 0.8017 | Val F1: 0.8930

Epoch 65/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [65/150] | LR: 8.41e-05 | Train Loss: 0.5158 | Train IoU: 0.7990 | Val Loss: 0.4994 | Val IoU: 0.8043 | Val F1: 0.8943

Epoch 66/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [66/150] | LR: 8.31e-05 | Train Loss: 0.4944 | Train IoU: 0.8149 | Val Loss: 0.5048 | Val IoU: 0.7957 | Val F1: 0.8874

Epoch 67/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [67/150] | LR: 8.21e-05 | Train Loss: 0.4939 | Train IoU: 0.8133 | Val Loss: 0.5332 | Val IoU: 0.7879 | Val F1: 0.8839

Epoch 68/150:   0%|          | 0/116 [00:00<?, ?it/s]

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process

Epoch [68/150] | LR: 8.10e-05 | Train Loss: 0.4829 | Train IoU: 0.8173 | Val Loss: 0.4874 | Val IoU: 0.8025 | Val F1: 0.8935

Epoch 69/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [69/150] | LR: 7.99e-05 | Train Loss: 0.4905 | Train IoU: 0.8131 | Val Loss: 0.4974 | Val IoU: 0.7989 | Val F1: 0.8908

Epoch 70/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [70/150] | LR: 7.88e-05 | Train Loss: 0.4842 | Train IoU: 0.8139 | Val Loss: 0.5041 | Val IoU: 0.8000 | Val F1: 0.8905

Epoch 71/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [71/150] | LR: 7.77e-05 | Train Loss: 0.4912 | Train IoU: 0.8117 | Val Loss: 0.4811 | Val IoU: 0.8067 | Val F1: 0.8960

Epoch 72/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [72/150] | LR: 7.66e-05 | Train Loss: 0.4818 | Train IoU: 0.8181 | Val Loss: 0.4985 | Val IoU: 0.7959 | Val F1: 0.8881

Epoch 73/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [73/150] | LR: 7.54e-05 | Train Loss: 0.4793 | Train IoU: 0.8167 | Val Loss: 0.4772 | Val IoU: 0.8086 | Val F1: 0.8976

Epoch 74/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [74/150] | LR: 7.42e-05 | Train Loss: 0.4729 | Train IoU: 0.8202 | Val Loss: 0.5000 | Val IoU: 0.8016 | Val F1: 0.8926

Epoch 75/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [75/150] | LR: 7.30e-05 | Train Loss: 0.4697 | Train IoU: 0.8152 | Val Loss: 0.4664 | Val IoU: 0.8046 | Val F1: 0.8941

Epoch 76/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [76/150] | LR: 7.18e-05 | Train Loss: 0.4661 | Train IoU: 0.8175 | Val Loss: 0.4871 | Val IoU: 0.8028 | Val F1: 0.8929

Epoch 77/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [77/150] | LR: 7.05e-05 | Train Loss: 0.4786 | Train IoU: 0.8150 | Val Loss: 0.4776 | Val IoU: 0.8097 | Val F1: 0.8971

Epoch 78/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [78/150] | LR: 6.93e-05 | Train Loss: 0.4622 | Train IoU: 0.8247 | Val Loss: 0.4681 | Val IoU: 0.8046 | Val F1: 0.8932

Epoch 79/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [79/150] | LR: 6.80e-05 | Train Loss: 0.4506 | Train IoU: 0.8265 | Val Loss: 0.4755 | Val IoU: 0.8043 | Val F1: 0.8934

Epoch 80/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [80/150] | LR: 6.67e-05 | Train Loss: 0.4674 | Train IoU: 0.8174 | Val Loss: 0.4710 | Val IoU: 0.8098 | Val F1: 0.8960

Epoch 81/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [81/150] | LR: 6.55e-05 | Train Loss: 0.4562 | Train IoU: 0.8233 | Val Loss: 0.4816 | Val IoU: 0.8052 | Val F1: 0.8948

Epoch 82/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [82/150] | LR: 6.41e-05 | Train Loss: 0.4515 | Train IoU: 0.8256 | Val Loss: 0.4735 | Val IoU: 0.8050 | Val F1: 0.8928

Epoch 83/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [83/150] | LR: 6.28e-05 | Train Loss: 0.4476 | Train IoU: 0.8264 | Val Loss: 0.4825 | Val IoU: 0.8015 | Val F1: 0.8921

Epoch 84/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [84/150] | LR: 6.15e-05 | Train Loss: 0.4495 | Train IoU: 0.8275 | Val Loss: 0.4869 | Val IoU: 0.7968 | Val F1: 0.8875

Epoch 85/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [85/150] | LR: 6.02e-05 | Train Loss: 0.4515 | Train IoU: 0.8217 | Val Loss: 0.4579 | Val IoU: 0.8096 | Val F1: 0.8974

Epoch 86/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [86/150] | LR: 5.88e-05 | Train Loss: 0.4380 | Train IoU: 0.8271 | Val Loss: 0.4613 | Val IoU: 0.8069 | Val F1: 0.8964

Epoch 87/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [87/150] | LR: 5.75e-05 | Train Loss: 0.4374 | Train IoU: 0.8320 | Val Loss: 0.4794 | Val IoU: 0.8037 | Val F1: 0.8937

Epoch 88/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [88/150] | LR: 5.61e-05 | Train Loss: 0.4425 | Train IoU: 0.8272 | Val Loss: 0.4735 | Val IoU: 0.8078 | Val F1: 0.8940

Epoch 89/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [89/150] | LR: 5.48e-05 | Train Loss: 0.4339 | Train IoU: 0.8318 | Val Loss: 0.5112 | Val IoU: 0.7899 | Val F1: 0.8827

Epoch 90/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [90/150] | LR: 5.34e-05 | Train Loss: 0.4251 | Train IoU: 0.8343 | Val Loss: 0.4648 | Val IoU: 0.8086 | Val F1: 0.8951

Epoch 91/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [91/150] | LR: 5.20e-05 | Train Loss: 0.4329 | Train IoU: 0.8328 | Val Loss: 0.4611 | Val IoU: 0.8059 | Val F1: 0.8953

Epoch 92/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [92/150] | LR: 5.07e-05 | Train Loss: 0.4458 | Train IoU: 0.8229 | Val Loss: 0.4626 | Val IoU: 0.8080 | Val F1: 0.8948

Epoch 93/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [93/150] | LR: 4.93e-05 | Train Loss: 0.4362 | Train IoU: 0.8307 | Val Loss: 0.4669 | Val IoU: 0.8038 | Val F1: 0.8936

Epoch 94/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [94/150] | LR: 4.80e-05 | Train Loss: 0.4349 | Train IoU: 0.8334 | Val Loss: 0.4695 | Val IoU: 0.8092 | Val F1: 0.8957

Epoch 95/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [95/150] | LR: 4.66e-05 | Train Loss: 0.4273 | Train IoU: 0.8291 | Val Loss: 0.4596 | Val IoU: 0.8061 | Val F1: 0.8940

Epoch 96/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [96/150] | LR: 4.52e-05 | Train Loss: 0.4228 | Train IoU: 0.8326 | Val Loss: 0.4719 | Val IoU: 0.8037 | Val F1: 0.8926

Epoch 97/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [97/150] | LR: 4.39e-05 | Train Loss: 0.4242 | Train IoU: 0.8312 | Val Loss: 0.4727 | Val IoU: 0.8055 | Val F1: 0.8941

Epoch 98/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [98/150] | LR: 4.25e-05 | Train Loss: 0.4238 | Train IoU: 0.8346 | Val Loss: 0.4510 | Val IoU: 0.8062 | Val F1: 0.8952

Epoch 99/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [99/150] | LR: 4.12e-05 | Train Loss: 0.4276 | Train IoU: 0.8313 | Val Loss: 0.4701 | Val IoU: 0.8067 | Val F1: 0.8949

Epoch 100/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [100/150] | LR: 3.98e-05 | Train Loss: 0.4245 | Train IoU: 0.8369 | Val Loss: 0.4628 | Val IoU: 0.8080 | Val F1: 0.8957

Epoch 101/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [101/150] | LR: 3.85e-05 | Train Loss: 0.4127 | Train IoU: 0.8364 | Val Loss: 0.4544 | Val IoU: 0.8052 | Val F1: 0.8949

Epoch 102/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [102/150] | LR: 3.72e-05 | Train Loss: 0.4103 | Train IoU: 0.8381 | Val Loss: 0.4600 | Val IoU: 0.8079 | Val F1: 0.8960

Epoch 103/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [103/150] | LR: 3.59e-05 | Train Loss: 0.4181 | Train IoU: 0.8374 | Val Loss: 0.4659 | Val IoU: 0.8077 | Val F1: 0.8951

Epoch 104/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [104/150] | LR: 3.45e-05 | Train Loss: 0.4133 | Train IoU: 0.8402 | Val Loss: 0.4549 | Val IoU: 0.8119 | Val F1: 0.8979
Checkpoint terbaik disimpan (Val IoU=0.8119)

Epoch 105/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [105/150] | LR: 3.33e-05 | Train Loss: 0.4061 | Train IoU: 0.8408 | Val Loss: 0.4481 | Val IoU: 0.8119 | Val F1: 0.8979
Checkpoint terbaik disimpan (Val IoU=0.8119)

Epoch 106/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [106/150] | LR: 3.20e-05 | Train Loss: 0.4066 | Train IoU: 0.8421 | Val Loss: 0.4587 | Val IoU: 0.8032 | Val F1: 0.8931

Epoch 107/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [107/150] | LR: 3.07e-05 | Train Loss: 0.4141 | Train IoU: 0.8376 | Val Loss: 0.4545 | Val IoU: 0.8039 | Val F1: 0.8935

Epoch 108/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [108/150] | LR: 2.95e-05 | Train Loss: 0.4127 | Train IoU: 0.8362 | Val Loss: 0.4560 | Val IoU: 0.8078 | Val F1: 0.8960

Epoch 109/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [109/150] | LR: 2.82e-05 | Train Loss: 0.4081 | Train IoU: 0.8429 | Val Loss: 0.4497 | Val IoU: 0.8080 | Val F1: 0.8962

Epoch 110/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [110/150] | LR: 2.70e-05 | Train Loss: 0.4073 | Train IoU: 0.8391 | Val Loss: 0.4487 | Val IoU: 0.8088 | Val F1: 0.8972

Epoch 111/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [111/150] | LR: 2.58e-05 | Train Loss: 0.4050 | Train IoU: 0.8390 | Val Loss: 0.4571 | Val IoU: 0.8041 | Val F1: 0.8945

Epoch 112/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [112/150] | LR: 2.46e-05 | Train Loss: 0.4046 | Train IoU: 0.8406 | Val Loss: 0.4690 | Val IoU: 0.8020 | Val F1: 0.8926

Epoch 113/150:   0%|          | 0/116 [00:00<?, ?it/s]

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^AssertionError
: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionErrorcan only test a child process:
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
Traceback (most recent call last):
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process

Epoch [113/150] | LR: 2.34e-05 | Train Loss: 0.4027 | Train IoU: 0.8418 | Val Loss: 0.4725 | Val IoU: 0.7972 | Val F1: 0.8898

Epoch 114/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [114/150] | LR: 2.23e-05 | Train Loss: 0.4112 | Train IoU: 0.8355 | Val Loss: 0.4540 | Val IoU: 0.8079 | Val F1: 0.8961

Epoch 115/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [115/150] | LR: 2.12e-05 | Train Loss: 0.3952 | Train IoU: 0.8435 | Val Loss: 0.4418 | Val IoU: 0.8143 | Val F1: 0.8996
Checkpoint terbaik disimpan (Val IoU=0.8143)

Epoch 116/150:   0%|          | 0/116 [00:00<?, ?it/s]

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process

Epoch [116/150] | LR: 2.01e-05 | Train Loss: 0.3928 | Train IoU: 0.8496 | Val Loss: 0.4516 | Val IoU: 0.8110 | Val F1: 0.8983

Epoch 117/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [117/150] | LR: 1.90e-05 | Train Loss: 0.4057 | Train IoU: 0.8387 | Val Loss: 0.4628 | Val IoU: 0.8055 | Val F1: 0.8940

Epoch 118/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [118/150] | LR: 1.79e-05 | Train Loss: 0.4070 | Train IoU: 0.8413 | Val Loss: 0.4521 | Val IoU: 0.8095 | Val F1: 0.8967

Epoch 119/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [119/150] | LR: 1.69e-05 | Train Loss: 0.4028 | Train IoU: 0.8431 | Val Loss: 0.4655 | Val IoU: 0.8068 | Val F1: 0.8952

Epoch 120/150:   0%|          | 0/116 [00:00<?, ?it/s]

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^AssertionError
: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process

Epoch [120/150] | LR: 1.59e-05 | Train Loss: 0.4031 | Train IoU: 0.8420 | Val Loss: 0.4557 | Val IoU: 0.8072 | Val F1: 0.8953

Epoch 121/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [121/150] | LR: 1.49e-05 | Train Loss: 0.3920 | Train IoU: 0.8441 | Val Loss: 0.4670 | Val IoU: 0.8024 | Val F1: 0.8915

Epoch 122/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [122/150] | LR: 1.39e-05 | Train Loss: 0.3909 | Train IoU: 0.8490 | Val Loss: 0.4491 | Val IoU: 0.8108 | Val F1: 0.8978

Epoch 123/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [123/150] | LR: 1.30e-05 | Train Loss: 0.3981 | Train IoU: 0.8415 | Val Loss: 0.4546 | Val IoU: 0.8088 | Val F1: 0.8966

Epoch 124/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [124/150] | LR: 1.21e-05 | Train Loss: 0.3897 | Train IoU: 0.8456 | Val Loss: 0.4678 | Val IoU: 0.8029 | Val F1: 0.8927

Epoch 125/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [125/150] | LR: 1.12e-05 | Train Loss: 0.4002 | Train IoU: 0.8439 | Val Loss: 0.4677 | Val IoU: 0.8033 | Val F1: 0.8931

Epoch 126/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [126/150] | LR: 1.04e-05 | Train Loss: 0.3831 | Train IoU: 0.8487 | Val Loss: 0.4484 | Val IoU: 0.8098 | Val F1: 0.8969

Epoch 127/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [127/150] | LR: 9.55e-06 | Train Loss: 0.3816 | Train IoU: 0.8507 | Val Loss: 0.4661 | Val IoU: 0.8094 | Val F1: 0.8964

Epoch 128/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [128/150] | LR: 8.76e-06 | Train Loss: 0.3928 | Train IoU: 0.8459 | Val Loss: 0.4607 | Val IoU: 0.8026 | Val F1: 0.8934

Epoch 129/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [129/150] | LR: 8.00e-06 | Train Loss: 0.3883 | Train IoU: 0.8481 | Val Loss: 0.4618 | Val IoU: 0.8057 | Val F1: 0.8948

Epoch 130/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [130/150] | LR: 7.28e-06 | Train Loss: 0.3840 | Train IoU: 0.8509 | Val Loss: 0.4615 | Val IoU: 0.8078 | Val F1: 0.8960

Epoch 131/150:   0%|          | 0/116 [00:00<?, ?it/s]

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process

Epoch [131/150] | LR: 6.59e-06 | Train Loss: 0.3968 | Train IoU: 0.8440 | Val Loss: 0.4569 | Val IoU: 0.8039 | Val F1: 0.8936

Epoch 132/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [132/150] | LR: 5.92e-06 | Train Loss: 0.3851 | Train IoU: 0.8475 | Val Loss: 0.4635 | Val IoU: 0.8031 | Val F1: 0.8929

Epoch 133/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [133/150] | LR: 5.30e-06 | Train Loss: 0.3932 | Train IoU: 0.8469 | Val Loss: 0.4557 | Val IoU: 0.8050 | Val F1: 0.8949

Epoch 134/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [134/150] | LR: 4.70e-06 | Train Loss: 0.3922 | Train IoU: 0.8461 | Val Loss: 0.4582 | Val IoU: 0.8046 | Val F1: 0.8936

Epoch 135/150:   0%|          | 0/116 [00:00<?, ?it/s]

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
      File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process

Epoch [135/150] | LR: 4.14e-06 | Train Loss: 0.3912 | Train IoU: 0.8483 | Val Loss: 0.4527 | Val IoU: 0.8082 | Val F1: 0.8962

Epoch 136/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [136/150] | LR: 3.61e-06 | Train Loss: 0.3919 | Train IoU: 0.8427 | Val Loss: 0.4554 | Val IoU: 0.8043 | Val F1: 0.8938

Epoch 137/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [137/150] | LR: 3.12e-06 | Train Loss: 0.3958 | Train IoU: 0.8455 | Val Loss: 0.4567 | Val IoU: 0.8044 | Val F1: 0.8940

Epoch 138/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [138/150] | LR: 2.66e-06 | Train Loss: 0.3914 | Train IoU: 0.8461 | Val Loss: 0.4590 | Val IoU: 0.8064 | Val F1: 0.8951

Epoch 139/150:   0%|          | 0/116 [00:00<?, ?it/s]

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb059ce2c00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only test a child process

Epoch [139/150] | LR: 2.24e-06 | Train Loss: 0.3864 | Train IoU: 0.8517 | Val Loss: 0.4558 | Val IoU: 0.8058 | Val F1: 0.8945

Epoch 140/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [140/150] | LR: 1.85e-06 | Train Loss: 0.3871 | Train IoU: 0.8509 | Val Loss: 0.4592 | Val IoU: 0.8019 | Val F1: 0.8913

Epoch 141/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [141/150] | LR: 1.50e-06 | Train Loss: 0.3977 | Train IoU: 0.8474 | Val Loss: 0.4529 | Val IoU: 0.8084 | Val F1: 0.8962

Epoch 142/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [142/150] | LR: 1.19e-06 | Train Loss: 0.3867 | Train IoU: 0.8496 | Val Loss: 0.4546 | Val IoU: 0.8088 | Val F1: 0.8964

Epoch 143/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [143/150] | LR: 9.11e-07 | Train Loss: 0.3939 | Train IoU: 0.8448 | Val Loss: 0.4691 | Val IoU: 0.8051 | Val F1: 0.8937

Epoch 144/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [144/150] | LR: 6.70e-07 | Train Loss: 0.3941 | Train IoU: 0.8433 | Val Loss: 0.4472 | Val IoU: 0.8097 | Val F1: 0.8972

Epoch 145/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [145/150] | LR: 4.66e-07 | Train Loss: 0.3821 | Train IoU: 0.8511 | Val Loss: 0.4529 | Val IoU: 0.8082 | Val F1: 0.8966

Epoch 146/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [146/150] | LR: 2.98e-07 | Train Loss: 0.3879 | Train IoU: 0.8517 | Val Loss: 0.4525 | Val IoU: 0.8065 | Val F1: 0.8953

Epoch 147/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [147/150] | LR: 1.68e-07 | Train Loss: 0.3852 | Train IoU: 0.8490 | Val Loss: 0.4480 | Val IoU: 0.8060 | Val F1: 0.8952

Epoch 148/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [148/150] | LR: 7.46e-08 | Train Loss: 0.3881 | Train IoU: 0.8468 | Val Loss: 0.4466 | Val IoU: 0.8086 | Val F1: 0.8965

Epoch 149/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [149/150] | LR: 1.87e-08 | Train Loss: 0.3783 | Train IoU: 0.8527 | Val Loss: 0.4586 | Val IoU: 0.8043 | Val F1: 0.8942

Epoch 150/150:   0%|          | 0/116 [00:00<?, ?it/s]

Epoch [150/150] | LR: 0.00e+00 | Train Loss: 0.3862 | Train IoU: 0.8489 | Val Loss: 0.4437 | Val IoU: 0.8080 | Val F1: 0.8965
Training selesai.

,epoch,lr,train_loss,train_iou,val_loss,val_iou,val_precision,val_recall,val_f1
145,146,2.982166e-07,0.387936,0.851732,0.452475,0.806463,0.896146,0.900322,0.895290
146,147,1.678199e-07,0.385231,0.849000,0.448050,0.805990,0.906486,0.889700,0.895226
147,148,7.460983e-08,0.388060,0.846814,0.446635,0.808559,0.901862,0.896920,0.896503
148,149,1.865594e-08,0.378292,0.852678,0.458594,0.804287,0.895937,0.898106,0.894199
149,150,0.000000e+00,0.386177,0.848940,0.443681,0.808036,0.906507,0.892066,0.896545

In [ ]:
@torch.no_grad()
def tta_predict_proba(model, images):
    # 4-way TTA: identity, HFlip, VFlip, HVFlip
    variants = [
        (lambda x: x, lambda y: y),
        (lambda x: torch.flip(x, dims=[3]), lambda y: torch.flip(y, dims=[3])),
        (lambda x: torch.flip(x, dims=[2]), lambda y: torch.flip(y, dims=[2])),
        (lambda x: torch.flip(x, dims=[2, 3]), lambda y: torch.flip(y, dims=[2, 3])),
    ]

    probs = []
    for aug, deaug in variants:
        logits = model(aug(images))
        probs.append(torch.sigmoid(deaug(logits)))
    return torch.mean(torch.stack(probs, dim=0), dim=0)


def dense_crf_refine(image_rgb_uint8, prob_map, n_iters=5):
    # prob_map shape: [H, W], values [0,1]
    if not HAS_DCRF:
        return prob_map

    h, w = prob_map.shape
    unary = np.stack([1.0 - prob_map, prob_map], axis=0)
    unary = unary_from_softmax(unary)

    d = dcrf.DenseCRF2D(w, h, 2)
    d.setUnaryEnergy(unary)
    d.addPairwiseGaussian(sxy=3, compat=3)
    d.addPairwiseBilateral(sxy=50, srgb=10, rgbim=image_rgb_uint8, compat=5)

    q = d.inference(n_iters)
    q = np.array(q).reshape((2, h, w))
    return q[1]


@torch.no_grad()
def evaluate_tta_crf(model, loader, device):
    model.eval()
    total_iou = 0.0
    total_precision = 0.0
    total_recall = 0.0
    total_f1 = 0.0
    count = 0

    for images, masks in tqdm(loader, desc="Eval TTA+CRF", leave=False):
        images = images.to(device)
        masks = masks.to(device)

        probs = tta_predict_proba(model, images)

        preds_list = []
        for i in range(probs.size(0)):
            prob = probs[i, 0].detach().cpu().numpy()
            img_np = images[i].detach().cpu().numpy().transpose(1, 2, 0)
            img_np = np.clip(
                img_np * np.array([0.229, 0.224, 0.225]) + np.array([0.485, 0.456, 0.406]),
                0,
                1,
            )
            img_uint8 = (img_np * 255).astype(np.uint8)
            prob_refined = dense_crf_refine(img_uint8, prob)
            preds_list.append((prob_refined > 0.5).astype(np.float32))

        preds = torch.from_numpy(np.stack(preds_list)).unsqueeze(1).to(device)

        tp = (preds * masks).sum().item()
        fp = (preds * (1 - masks)).sum().item()
        fn = ((1 - preds) * masks).sum().item()
        union = preds.sum().item() + masks.sum().item() - tp

        iou = tp / (union + 1e-8)
        precision = tp / (tp + fp + 1e-8)
        recall = tp / (tp + fn + 1e-8)
        f1 = 2 * precision * recall / (precision + recall + 1e-8)

        total_iou += iou
        total_precision += precision
        total_recall += recall
        total_f1 += f1
        count += 1

    count = max(count, 1)
    return {
        "iou": total_iou / count,
        "precision": total_precision / count,
        "recall": total_recall / count,
        "f1": total_f1 / count,
    }


# Load checkpoint terbaik sebelum evaluasi akhir
if os.path.exists(CONFIG["CHECKPOINT_PATH"]):
    ckpt = torch.load(CONFIG["CHECKPOINT_PATH"], map_location=CONFIG["DEVICE"])
    model.load_state_dict(ckpt["model_state_dict"])
    print(f"Checkpoint loaded dari epoch {ckpt['epoch']} | best IoU={ckpt['best_val_iou']:.4f}")
else:
    print("Checkpoint belum ditemukan, evaluasi pakai bobot saat ini.")

val_plain = validate_one_epoch(model, val_loader, CONFIG["DEVICE"])
val_tta_crf = evaluate_tta_crf(model, val_loader, CONFIG["DEVICE"])

print("\n--- Validation (Plain) ---")
print(val_plain)
print("\n--- Validation (TTA + DenseCRF) ---")
print(val_tta_crf)

In [ ]:
@torch.no_grad()
def show_predictions(model, loader, device, num_samples=3):
    model.eval()
    images, masks = next(iter(loader))
    images = images.to(device)
    masks = masks.to(device)

    probs = tta_predict_proba(model, images)
    preds = (probs > 0.5).float()

    n = min(num_samples, images.size(0))
    fig, axes = plt.subplots(n, 3, figsize=(15, 5 * n))
    if n == 1:
        axes = np.expand_dims(axes, axis=0)

    for i in range(n):
        img_np = images[i].detach().cpu().numpy().transpose(1, 2, 0)
        img_np = np.clip(
            img_np * np.array([0.229, 0.224, 0.225]) + np.array([0.485, 0.456, 0.406]),
            0,
            1,
        )
        gt = masks[i, 0].detach().cpu().numpy()
        pr = preds[i, 0].detach().cpu().numpy()

        axes[i, 0].imshow(img_np)
        axes[i, 0].set_title("Image")
        axes[i, 0].axis("off")

        axes[i, 1].imshow(gt, cmap="gray")
        axes[i, 1].set_title("Ground Truth")
        axes[i, 1].axis("off")

        axes[i, 2].imshow(img_np)
        axes[i, 2].imshow(pr, cmap="jet", alpha=0.4)
        axes[i, 2].set_title("Prediction")
        axes[i, 2].axis("off")

    plt.tight_layout()
    plt.show()


show_predictions(model, val_loader, CONFIG["DEVICE"], num_samples=3)